/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mongodb.labs.ftdc;

import com.mongodb.MongoClientSettings;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import org.bson.Document;
import org.junit.jupiter.api.Test;

class MongoTelemetryTest {
    @Test
    void testTelemetry() throws InterruptedException {
        MongoClientSettings.Builder clientSettingsBuilder = MongoClientSettings.builder();
        MongoTelemetry.addTelemetryListeners(clientSettingsBuilder);
        MongoClient client = MongoClients.create(clientSettingsBuilder.build());

        for (int i = 0; i < 30; i++) {
            client.getDatabase("admin").runCommand(new Document("ping", 1));
            Thread.sleep(100);
        }
    }
}
