/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    mavenLocal()
}

java {
    sourceCompatibility = JavaVersion.VERSION_19
}

tasks.withType<JavaCompile> {
    options.compilerArgs.add("--enable-preview")
}
tasks.test {
    useJUnitPlatform()
    jvmArgs("--enable-preview")
}


dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")

    // Use sync driver for testing
    testImplementation("org.mongodb:mongodb-driver-sync:4.10.0-SNAPSHOT")

    testImplementation("ch.qos.logback:logback-classic:1.4.6")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.mongodb:mongodb-driver-core:4.10.0-SNAPSHOT")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "org.mongodb"
            artifactId = "mongodb-ftdc"
            version = "1.0-SNAPSHOT"

            from(components["java"])
        }
    }
}

